/* tslint:disable */
/* eslint-disable */
/**
 * LAPRAS Public API
 * LAPRAS公開ページAPIの仕様書
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ブログ記事
 * @export
 * @interface BlogArticle
 */
export interface BlogArticle {
    /**
     * 
     * @type {string}
     * @memberof BlogArticle
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof BlogArticle
     */
    url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BlogArticle
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BlogArticle
     */
    postedAt: string;
}

/**
 * Check if a given object implements the BlogArticle interface.
 */
export function instanceOfBlogArticle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "postedAt" in value;

    return isInstance;
}

export function BlogArticleFromJSON(json: any): BlogArticle {
    return BlogArticleFromJSONTyped(json, false);
}

export function BlogArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlogArticle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'url': json['url'],
        'tags': json['tags'],
        'postedAt': json['posted_at'],
    };
}

export function BlogArticleToJSON(value?: BlogArticle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'url': value.url,
        'tags': value.tags,
        'posted_at': value.postedAt,
    };
}

