/* tslint:disable */
/* eslint-disable */
/**
 * LAPRAS Public API
 * LAPRAS公開ページAPIの仕様書
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GitHubRepositoryLanguagesInner
 */
export interface GitHubRepositoryLanguagesInner {
    /**
     * 
     * @type {string}
     * @memberof GitHubRepositoryLanguagesInner
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof GitHubRepositoryLanguagesInner
     */
    bytes: number;
}

/**
 * Check if a given object implements the GitHubRepositoryLanguagesInner interface.
 */
export function instanceOfGitHubRepositoryLanguagesInner(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "bytes" in value;

    return isInstance;
}

export function GitHubRepositoryLanguagesInnerFromJSON(json: any): GitHubRepositoryLanguagesInner {
    return GitHubRepositoryLanguagesInnerFromJSONTyped(json, false);
}

export function GitHubRepositoryLanguagesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): GitHubRepositoryLanguagesInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'bytes': json['bytes'],
    };
}

export function GitHubRepositoryLanguagesInnerToJSON(value?: GitHubRepositoryLanguagesInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'bytes': value.bytes,
    };
}

