/* tslint:disable */
/* eslint-disable */
/**
 * LAPRAS Public API
 * LAPRAS公開ページAPIの仕様書
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Qiita記事
 * @export
 * @interface QiitaArticle
 */
export interface QiitaArticle {
    /**
     * 
     * @type {string}
     * @memberof QiitaArticle
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof QiitaArticle
     */
    url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof QiitaArticle
     */
    tags: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof QiitaArticle
     */
    headlines: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof QiitaArticle
     */
    stockersCount: number;
    /**
     * 
     * @type {string}
     * @memberof QiitaArticle
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the QiitaArticle interface.
 */
export function instanceOfQiitaArticle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "headlines" in value;
    isInstance = isInstance && "stockersCount" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function QiitaArticleFromJSON(json: any): QiitaArticle {
    return QiitaArticleFromJSONTyped(json, false);
}

export function QiitaArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): QiitaArticle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'url': json['url'],
        'tags': json['tags'],
        'headlines': json['headlines'],
        'stockersCount': json['stockers_count'],
        'updatedAt': json['updated_at'],
    };
}

export function QiitaArticleToJSON(value?: QiitaArticle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'url': value.url,
        'tags': value.tags,
        'headlines': value.headlines,
        'stockers_count': value.stockersCount,
        'updated_at': value.updatedAt,
    };
}

