/* tslint:disable */
/* eslint-disable */
/**
 * LAPRAS Public API
 * LAPRAS公開ページAPIの仕様書
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * SpeakerDeckスライド
 * @export
 * @interface SpeakerDeckSlide
 */
export interface SpeakerDeckSlide {
    /**
     * 
     * @type {string}
     * @memberof SpeakerDeckSlide
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof SpeakerDeckSlide
     */
    url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SpeakerDeckSlide
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SpeakerDeckSlide
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof SpeakerDeckSlide
     */
    viewCount: number;
    /**
     * 
     * @type {number}
     * @memberof SpeakerDeckSlide
     */
    starCount: number;
    /**
     * 
     * @type {string}
     * @memberof SpeakerDeckSlide
     */
    presentationDate: string;
}

/**
 * Check if a given object implements the SpeakerDeckSlide interface.
 */
export function instanceOfSpeakerDeckSlide(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "tags" in value;
    isInstance = isInstance && "description" in value;
    isInstance = isInstance && "viewCount" in value;
    isInstance = isInstance && "starCount" in value;
    isInstance = isInstance && "presentationDate" in value;

    return isInstance;
}

export function SpeakerDeckSlideFromJSON(json: any): SpeakerDeckSlide {
    return SpeakerDeckSlideFromJSONTyped(json, false);
}

export function SpeakerDeckSlideFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpeakerDeckSlide {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'url': json['url'],
        'tags': json['tags'],
        'description': json['description'],
        'viewCount': json['view_count'],
        'starCount': json['star_count'],
        'presentationDate': json['presentation_date'],
    };
}

export function SpeakerDeckSlideToJSON(value?: SpeakerDeckSlide | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'url': value.url,
        'tags': value.tags,
        'description': value.description,
        'view_count': value.viewCount,
        'star_count': value.starCount,
        'presentation_date': value.presentationDate,
    };
}

