/* tslint:disable */
/* eslint-disable */
/**
 * LAPRAS Public API
 * LAPRAS公開ページAPIの仕様書
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Zenn記事
 * @export
 * @interface ZennArticle
 */
export interface ZennArticle {
    /**
     * 
     * @type {string}
     * @memberof ZennArticle
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof ZennArticle
     */
    url: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ZennArticle
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof ZennArticle
     */
    postedAt?: string;
}

/**
 * Check if a given object implements the ZennArticle interface.
 */
export function instanceOfZennArticle(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "title" in value;
    isInstance = isInstance && "url" in value;
    isInstance = isInstance && "tags" in value;

    return isInstance;
}

export function ZennArticleFromJSON(json: any): ZennArticle {
    return ZennArticleFromJSONTyped(json, false);
}

export function ZennArticleFromJSONTyped(json: any, ignoreDiscriminator: boolean): ZennArticle {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'url': json['url'],
        'tags': json['tags'],
        'postedAt': !exists(json, 'posted_at') ? undefined : json['posted_at'],
    };
}

export function ZennArticleToJSON(value?: ZennArticle | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'url': value.url,
        'tags': value.tags,
        'posted_at': value.postedAt,
    };
}

