/* tslint:disable */
/* eslint-disable */
/**
 * LAPRAS Public API
 * LAPRAS公開ページAPIの仕様書
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetLaprasData200Response,
} from '../models/index';
import {
    GetLaprasData200ResponseFromJSON,
    GetLaprasData200ResponseToJSON,
} from '../models/index';

export interface GetLaprasDataRequest {
    shareId: string;
}

/**
 * 
 */
export class LaprasPublicApi extends runtime.BaseAPI {

    /**
     * 
     * Get LAPRAS Data
     */
    async getLaprasDataRaw(requestParameters: GetLaprasDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetLaprasData200Response>> {
        if (requestParameters.shareId === null || requestParameters.shareId === undefined) {
            throw new runtime.RequiredError('shareId','Required parameter requestParameters.shareId was null or undefined when calling getLaprasData.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/{shareId}.json`.replace(`{${"shareId"}}`, encodeURIComponent(String(requestParameters.shareId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetLaprasData200ResponseFromJSON(jsonValue));
    }

    /**
     * 
     * Get LAPRAS Data
     */
    async getLaprasData(requestParameters: GetLaprasDataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetLaprasData200Response> {
        const response = await this.getLaprasDataRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
